development:
  adapter:  postgresql
  host:     localhost
  username: acanyon
  database: momentsphotoshare-dev

test:
  adapter:  postgresql
  host:     localhost
  username: acanyon
  database: momentsphotoshare-test
